/*
 * This file is part of the ZombieBox package.
 *
 * Copyright (c) 2011-2016, Interfaced
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Data in this file is generated by npm run extract-data and should not be edited manually.
 * Data comes from Unicode CLDR project: http://cldr.unicode.org/
 */
goog.provide('zb.i18n.datetime.Formats');


/**
 * @type {Object.<zb.i18n.Locale, zb.i18n.datetime.Format>}
 */
zb.i18n.datetime.Formats = {
	"en": {
		"formats": {
			"date": {
				"full": "EEEE, MMMM d, y",
				"long": "MMMM d, y",
				"medium": "MMM d, y",
				"short": "M/d/yy"
			},
			"time": {
				"full": "h:mm:ss a zzzz",
				"long": "h:mm:ss a z",
				"medium": "h:mm:ss a",
				"short": "h:mm a"
			},
			"dateTime": {
				"short": "[date], [time]",
				"medium": "[date], [time]",
				"full": "[date] 'at' [time]",
				"long": "[date] 'at' [time]"
			}
		},
		"calendar": {
			"days": {
				"wide": {
					"0": "Sunday",
					"1": "Monday",
					"2": "Tuesday",
					"3": "Wednesday",
					"4": "Thursday",
					"5": "Friday",
					"6": "Saturday"
				},
				"narrow": {
					"0": "S",
					"1": "M",
					"2": "T",
					"3": "W",
					"4": "T",
					"5": "F",
					"6": "S"
				},
				"abbreviated": {
					"0": "Sun",
					"1": "Mon",
					"2": "Tue",
					"3": "Wed",
					"4": "Thu",
					"5": "Fri",
					"6": "Sat"
				}
			},
			"months": {
				"wide": {
					"0": "January",
					"1": "February",
					"2": "March",
					"3": "April",
					"4": "May",
					"5": "June",
					"6": "July",
					"7": "August",
					"8": "September",
					"9": "October",
					"10": "November",
					"11": "December"
				},
				"narrow": {
					"0": "J",
					"1": "F",
					"2": "M",
					"3": "A",
					"4": "M",
					"5": "J",
					"6": "J",
					"7": "A",
					"8": "S",
					"9": "O",
					"10": "N",
					"11": "D"
				},
				"abbreviated": {
					"0": "Jan",
					"1": "Feb",
					"2": "Mar",
					"3": "Apr",
					"4": "May",
					"5": "Jun",
					"6": "Jul",
					"7": "Aug",
					"8": "Sep",
					"9": "Oct",
					"10": "Nov",
					"11": "Dec"
				}
			},
			"dayPeriods": {
				"am": "AM",
				"pm": "PM"
			}
		}
	},
	"ru": {
		"formats": {
			"date": {
				"full": "EEEE, d MMMM y 'г'.",
				"long": "d MMMM y 'г'.",
				"medium": "d MMM y 'г'.",
				"short": "dd.MM.yy"
			},
			"time": {
				"full": "H:mm:ss zzzz",
				"long": "H:mm:ss z",
				"medium": "H:mm:ss",
				"short": "H:mm"
			},
			"dateTime": {
				"short": "[date], [time]",
				"medium": "[date], [time]",
				"full": "[date], [time]",
				"long": "[date], [time]"
			}
		},
		"calendar": {
			"days": {
				"wide": {
					"0": "воскресенье",
					"1": "понедельник",
					"2": "вторник",
					"3": "среда",
					"4": "четверг",
					"5": "пятница",
					"6": "суббота"
				},
				"narrow": {
					"0": "вс",
					"1": "пн",
					"2": "вт",
					"3": "ср",
					"4": "чт",
					"5": "пт",
					"6": "сб"
				},
				"abbreviated": {
					"0": "вс",
					"1": "пн",
					"2": "вт",
					"3": "ср",
					"4": "чт",
					"5": "пт",
					"6": "сб"
				}
			},
			"months": {
				"wide": {
					"0": "января",
					"1": "февраля",
					"2": "марта",
					"3": "апреля",
					"4": "мая",
					"5": "июня",
					"6": "июля",
					"7": "августа",
					"8": "сентября",
					"9": "октября",
					"10": "ноября",
					"11": "декабря"
				},
				"narrow": {
					"0": "Я",
					"1": "Ф",
					"2": "М",
					"3": "А",
					"4": "М",
					"5": "И",
					"6": "И",
					"7": "А",
					"8": "С",
					"9": "О",
					"10": "Н",
					"11": "Д"
				},
				"abbreviated": {
					"0": "янв.",
					"1": "февр.",
					"2": "мар.",
					"3": "апр.",
					"4": "мая",
					"5": "июн.",
					"6": "июл.",
					"7": "авг.",
					"8": "сент.",
					"9": "окт.",
					"10": "нояб.",
					"11": "дек."
				}
			},
			"dayPeriods": {
				"am": "ДП",
				"pm": "ПП"
			}
		}
	}
};


/**
 * @typedef {{
 *     formats: {
 *         date: Object<zb.i18n.datetime.Form, string>,
 *         time: Object<zb.i18n.datetime.Form, string>,
 *         short: string,
 *         medium: string,
 *         full: string,
 *         long: string
 *     },
 *     calendar: {
 *         months: {
 *             narrow: Object<string, string>,
 *             short: Object<string, string>,
 *             long: Object<string, string>
 *         },
 *         days: {
 *             narrow: Object<string, string>,
 *             short: Object<string, string>,
 *             long: Object<string, string>
 *         },
 *         dayPeriods: {
 *             am: string,
 *             pm: string
 *         }
 *     }
 * }}
 */
zb.i18n.datetime.Format;
