/*
 * This file is part of the ZombieBox package.
 *
 * Copyright (c) 2011-2016, Interfaced
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Data in this file is generated by npm run extract-data and should not be edited manually.
 * Data comes from Unicode CLDR project: http://cldr.unicode.org/
 */
goog.provide('zb.i18n.numbers.currencies');


/**
 * @type {Object.<zb.i18n.Locale, Object.<zb.i18n.numbers.Currency, zb.i18n.numbers.CurrencyFormat>>}
 */
zb.i18n.numbers.currencies = {
	"en": {
		"AOA": {
			"narrowSymbol": "Kz"
		},
		"ARS": {
			"narrowSymbol": "$"
		},
		"AUD": {
			"symbol": "A$",
			"narrowSymbol": "$"
		},
		"BAM": {
			"narrowSymbol": "KM"
		},
		"BBD": {
			"narrowSymbol": "$"
		},
		"BDT": {
			"narrowSymbol": "৳"
		},
		"BMD": {
			"narrowSymbol": "$"
		},
		"BND": {
			"narrowSymbol": "$"
		},
		"BOB": {
			"narrowSymbol": "Bs"
		},
		"BRL": {
			"symbol": "R$",
			"narrowSymbol": "R$"
		},
		"BSD": {
			"narrowSymbol": "$"
		},
		"BWP": {
			"narrowSymbol": "P"
		},
		"BYR": {
			"narrowSymbol": "р."
		},
		"BZD": {
			"narrowSymbol": "$"
		},
		"CAD": {
			"symbol": "CA$",
			"narrowSymbol": "$"
		},
		"CLP": {
			"narrowSymbol": "$"
		},
		"CNY": {
			"symbol": "CN¥",
			"narrowSymbol": "¥"
		},
		"COP": {
			"narrowSymbol": "$"
		},
		"CRC": {
			"narrowSymbol": "₡"
		},
		"CUC": {
			"narrowSymbol": "$"
		},
		"CUP": {
			"narrowSymbol": "$"
		},
		"CZK": {
			"narrowSymbol": "Kč"
		},
		"DKK": {
			"narrowSymbol": "kr"
		},
		"DOP": {
			"narrowSymbol": "$"
		},
		"EGP": {
			"narrowSymbol": "E£"
		},
		"ESP": {
			"narrowSymbol": "₧"
		},
		"EUR": {
			"symbol": "€",
			"narrowSymbol": "€"
		},
		"FJD": {
			"narrowSymbol": "$"
		},
		"FKP": {
			"narrowSymbol": "£"
		},
		"GBP": {
			"symbol": "£",
			"narrowSymbol": "£"
		},
		"GEL": {
			"narrowSymbol": "₾"
		},
		"GIP": {
			"narrowSymbol": "£"
		},
		"GNF": {
			"narrowSymbol": "FG"
		},
		"GTQ": {
			"narrowSymbol": "Q"
		},
		"GYD": {
			"narrowSymbol": "$"
		},
		"HKD": {
			"symbol": "HK$",
			"narrowSymbol": "$"
		},
		"HNL": {
			"narrowSymbol": "L"
		},
		"HRK": {
			"narrowSymbol": "kn"
		},
		"HUF": {
			"narrowSymbol": "Ft"
		},
		"IDR": {
			"narrowSymbol": "Rp"
		},
		"ILS": {
			"symbol": "₪",
			"narrowSymbol": "₪"
		},
		"INR": {
			"symbol": "₹",
			"narrowSymbol": "₹"
		},
		"ISK": {
			"narrowSymbol": "kr"
		},
		"JMD": {
			"narrowSymbol": "$"
		},
		"JPY": {
			"symbol": "¥",
			"narrowSymbol": "¥"
		},
		"KHR": {
			"narrowSymbol": "៛"
		},
		"KMF": {
			"narrowSymbol": "CF"
		},
		"KPW": {
			"narrowSymbol": "₩"
		},
		"KRW": {
			"symbol": "₩",
			"narrowSymbol": "₩"
		},
		"KYD": {
			"narrowSymbol": "$"
		},
		"KZT": {
			"narrowSymbol": "₸"
		},
		"LAK": {
			"narrowSymbol": "₭"
		},
		"LBP": {
			"narrowSymbol": "L£"
		},
		"LKR": {
			"narrowSymbol": "Rs"
		},
		"LRD": {
			"narrowSymbol": "$"
		},
		"LTL": {
			"narrowSymbol": "Lt"
		},
		"LVL": {
			"narrowSymbol": "Ls"
		},
		"MGA": {
			"narrowSymbol": "Ar"
		},
		"MMK": {
			"narrowSymbol": "K"
		},
		"MNT": {
			"narrowSymbol": "₮"
		},
		"MUR": {
			"narrowSymbol": "Rs"
		},
		"MXN": {
			"symbol": "MX$",
			"narrowSymbol": "$"
		},
		"MYR": {
			"narrowSymbol": "RM"
		},
		"NAD": {
			"narrowSymbol": "$"
		},
		"NGN": {
			"narrowSymbol": "₦"
		},
		"NIO": {
			"narrowSymbol": "C$"
		},
		"NOK": {
			"narrowSymbol": "kr"
		},
		"NPR": {
			"narrowSymbol": "Rs"
		},
		"NZD": {
			"symbol": "NZ$",
			"narrowSymbol": "$"
		},
		"PHP": {
			"narrowSymbol": "₱"
		},
		"PKR": {
			"narrowSymbol": "Rs"
		},
		"PLN": {
			"narrowSymbol": "zł"
		},
		"PYG": {
			"narrowSymbol": "₲"
		},
		"RUB": {
			"narrowSymbol": "₽"
		},
		"RUR": {
			"narrowSymbol": "р."
		},
		"RWF": {
			"narrowSymbol": "RF"
		},
		"SBD": {
			"narrowSymbol": "$"
		},
		"SEK": {
			"narrowSymbol": "kr"
		},
		"SGD": {
			"narrowSymbol": "$"
		},
		"SHP": {
			"narrowSymbol": "£"
		},
		"SRD": {
			"narrowSymbol": "$"
		},
		"SSP": {
			"narrowSymbol": "£"
		},
		"STD": {
			"narrowSymbol": "Db"
		},
		"SYP": {
			"narrowSymbol": "£"
		},
		"THB": {
			"narrowSymbol": "฿"
		},
		"TOP": {
			"narrowSymbol": "T$"
		},
		"TRY": {
			"narrowSymbol": "₺"
		},
		"TTD": {
			"narrowSymbol": "$"
		},
		"TWD": {
			"symbol": "NT$",
			"narrowSymbol": "$"
		},
		"UAH": {
			"narrowSymbol": "₴"
		},
		"USD": {
			"symbol": "$",
			"narrowSymbol": "$"
		},
		"UYU": {
			"narrowSymbol": "$"
		},
		"VEF": {
			"narrowSymbol": "Bs"
		},
		"VND": {
			"symbol": "₫",
			"narrowSymbol": "₫"
		},
		"XAF": {
			"symbol": "FCFA"
		},
		"XCD": {
			"symbol": "EC$",
			"narrowSymbol": "$"
		},
		"XOF": {
			"symbol": "CFA"
		},
		"XPF": {
			"symbol": "CFPF"
		},
		"ZAR": {
			"narrowSymbol": "R"
		},
		"ZMW": {
			"narrowSymbol": "ZK"
		}
	},
	"ru": {
		"AOA": {
			"narrowSymbol": "Kz"
		},
		"ARS": {
			"narrowSymbol": "$"
		},
		"AUD": {
			"symbol": "A$",
			"narrowSymbol": "$"
		},
		"BAM": {
			"narrowSymbol": "KM"
		},
		"BBD": {
			"narrowSymbol": "$"
		},
		"BDT": {
			"narrowSymbol": "৳"
		},
		"BMD": {
			"narrowSymbol": "$"
		},
		"BND": {
			"narrowSymbol": "$"
		},
		"BOB": {
			"narrowSymbol": "Bs"
		},
		"BRL": {
			"symbol": "R$",
			"narrowSymbol": "R$"
		},
		"BSD": {
			"narrowSymbol": "$"
		},
		"BWP": {
			"narrowSymbol": "P"
		},
		"BYR": {
			"narrowSymbol": "р."
		},
		"BZD": {
			"narrowSymbol": "$"
		},
		"CAD": {
			"symbol": "CA$",
			"narrowSymbol": "$"
		},
		"CLP": {
			"narrowSymbol": "$"
		},
		"CNY": {
			"symbol": "CN¥",
			"narrowSymbol": "¥"
		},
		"COP": {
			"narrowSymbol": "$"
		},
		"CRC": {
			"narrowSymbol": "₡"
		},
		"CUC": {
			"narrowSymbol": "$"
		},
		"CUP": {
			"narrowSymbol": "$"
		},
		"CZK": {
			"narrowSymbol": "Kč"
		},
		"DKK": {
			"narrowSymbol": "kr"
		},
		"DOP": {
			"narrowSymbol": "$"
		},
		"EGP": {
			"narrowSymbol": "E£"
		},
		"ESP": {
			"narrowSymbol": "₧"
		},
		"EUR": {
			"symbol": "€",
			"narrowSymbol": "€"
		},
		"FJD": {
			"narrowSymbol": "$"
		},
		"FKP": {
			"narrowSymbol": "£"
		},
		"GBP": {
			"symbol": "£",
			"narrowSymbol": "£"
		},
		"GEL": {
			"narrowSymbol": "₾"
		},
		"GIP": {
			"narrowSymbol": "£"
		},
		"GNF": {
			"narrowSymbol": "FG"
		},
		"GTQ": {
			"narrowSymbol": "Q"
		},
		"GYD": {
			"narrowSymbol": "$"
		},
		"HKD": {
			"symbol": "HK$",
			"narrowSymbol": "$"
		},
		"HNL": {
			"narrowSymbol": "L"
		},
		"HRK": {
			"narrowSymbol": "kn"
		},
		"HUF": {
			"narrowSymbol": "Ft"
		},
		"IDR": {
			"narrowSymbol": "Rp"
		},
		"ILS": {
			"symbol": "₪",
			"narrowSymbol": "₪"
		},
		"INR": {
			"symbol": "₹",
			"narrowSymbol": "₹"
		},
		"ISK": {
			"narrowSymbol": "kr"
		},
		"JMD": {
			"narrowSymbol": "$"
		},
		"JPY": {
			"symbol": "¥",
			"narrowSymbol": "¥"
		},
		"KHR": {
			"narrowSymbol": "៛"
		},
		"KMF": {
			"narrowSymbol": "CF"
		},
		"KPW": {
			"narrowSymbol": "₩"
		},
		"KRW": {
			"symbol": "₩",
			"narrowSymbol": "₩"
		},
		"KYD": {
			"narrowSymbol": "$"
		},
		"KZT": {
			"narrowSymbol": "₸"
		},
		"LAK": {
			"narrowSymbol": "₭"
		},
		"LBP": {
			"narrowSymbol": "L£"
		},
		"LKR": {
			"narrowSymbol": "Rs"
		},
		"LRD": {
			"narrowSymbol": "$"
		},
		"LTL": {
			"narrowSymbol": "Lt"
		},
		"LVL": {
			"narrowSymbol": "Ls"
		},
		"MGA": {
			"narrowSymbol": "Ar"
		},
		"MMK": {
			"narrowSymbol": "K"
		},
		"MNT": {
			"narrowSymbol": "₮"
		},
		"MUR": {
			"narrowSymbol": "Rs"
		},
		"MXN": {
			"symbol": "MX$",
			"narrowSymbol": "$"
		},
		"MYR": {
			"narrowSymbol": "RM"
		},
		"NAD": {
			"narrowSymbol": "$"
		},
		"NGN": {
			"narrowSymbol": "₦"
		},
		"NIO": {
			"narrowSymbol": "C$"
		},
		"NOK": {
			"narrowSymbol": "kr"
		},
		"NPR": {
			"narrowSymbol": "Rs"
		},
		"NZD": {
			"symbol": "NZ$",
			"narrowSymbol": "$"
		},
		"PHP": {
			"narrowSymbol": "₱"
		},
		"PKR": {
			"narrowSymbol": "Rs"
		},
		"PLN": {
			"narrowSymbol": "zł"
		},
		"PYG": {
			"narrowSymbol": "₲"
		},
		"RUB": {
			"symbol": "₽",
			"narrowSymbol": "₽"
		},
		"RUR": {
			"symbol": "р.",
			"narrowSymbol": "р."
		},
		"RWF": {
			"narrowSymbol": "RF"
		},
		"SBD": {
			"narrowSymbol": "$"
		},
		"SEK": {
			"narrowSymbol": "kr"
		},
		"SGD": {
			"narrowSymbol": "$"
		},
		"SHP": {
			"narrowSymbol": "£"
		},
		"SRD": {
			"narrowSymbol": "$"
		},
		"SSP": {
			"narrowSymbol": "£"
		},
		"STD": {
			"narrowSymbol": "Db"
		},
		"SYP": {
			"narrowSymbol": "£"
		},
		"THB": {
			"symbol": "฿",
			"narrowSymbol": "฿"
		},
		"TMT": {
			"symbol": "ТМТ"
		},
		"TOP": {
			"narrowSymbol": "T$"
		},
		"TRY": {
			"narrowSymbol": "₺"
		},
		"TTD": {
			"narrowSymbol": "$"
		},
		"TWD": {
			"symbol": "NT$",
			"narrowSymbol": "NT$"
		},
		"UAH": {
			"symbol": "₴",
			"narrowSymbol": "₴"
		},
		"USD": {
			"symbol": "$",
			"narrowSymbol": "$"
		},
		"UYU": {
			"narrowSymbol": "$"
		},
		"VEF": {
			"narrowSymbol": "Bs"
		},
		"VND": {
			"symbol": "₫",
			"narrowSymbol": "₫"
		},
		"XAF": {
			"symbol": "FCFA"
		},
		"XCD": {
			"symbol": "EC$",
			"narrowSymbol": "$"
		},
		"XOF": {
			"symbol": "CFA"
		},
		"XPF": {
			"symbol": "CFPF"
		},
		"XXX": {
			"symbol": "XXXX"
		},
		"ZAR": {
			"narrowSymbol": "R"
		},
		"ZMW": {
			"narrowSymbol": "ZK"
		}
	}
};


/**
 * @typedef {{
 *    symbol: ?string,
 *    narrowSymbol: ?string
 * }}
 */
zb.i18n.numbers.CurrencyFormat;
