/*
 * This file is part of the ZombieBox package.
 *
 * Copyright (c) 2011-2016, Interfaced
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Data in this file is generated by npm run extract-data and should not be edited manually.
 * Data comes from Unicode CLDR project: http://cldr.unicode.org/
 */
goog.provide('zb.i18n.numbers.Formats');


/**
 * @type {Object.<zb.i18n.Locale, zb.i18n.numbers.Format>}
 */
zb.i18n.numbers.Formats = {
	"en": {
		"delimiters": {
			"decimal": ".",
			"group": ","
		},
		"currency": "[symbol][value]"
	},
	"ru": {
		"delimiters": {
			"decimal": ",",
			"group": " "
		},
		"currency": "[value] [symbol]"
	}
};


/**
 * @typedef {{
 *     delimiters: {
 *         decimal: string,
 *         group: string
 *     },
 *     currency: string
 * }}
 */
zb.i18n.numbers.Format;
